CREATE TABLE MERCHANT_ENTITY_USER (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY NOT NULL,
    USER_ID RAW(16)  NOT NULL,
    ENTITY_ID VARCHAR2(50),
    MID VARCHAR2(50),
    CREATED_BY	VARCHAR2(50)NOT NULL,
    CREATED_AT	NUMBER NOT NULL,
    UPDATED_BY	VARCHAR2(50) NOT NULL,
    UPDATED_AT	NUMBER NOT NULL,
    CONSTRAINT FK_MERCHANT_ENTITY_USER_ID  FOREIGN KEY (USER_ID) REFERENCES MERCHANT_USER(ID), -- Foreign Key to `MERCHANT USER` table
    CONSTRAINT FK_MERCHANT_ENTITY_USER_MID  FOREIGN KEY (MID) REFERENCES MERCHANT_INFO(MID) -- Foreign Key to `MERCHANT Info` table
);


CREATE TABLE MERCHANT_ENTITY_GROUP (
    ID RAW(16)  DEFAULT SYS_GUID() PRIMARY KEY,
    MID VARCHAR2(50) NOT NULL,
    ENTITY_ID VARCHAR2(50) NOT NULL,
    CREATED_BY	VARCHAR2(50) NOT NULL,
    CREATED_AT	NUMBER NOT NULL,
    UPDATED_BY	VARCHAR2(50) NOT NULL,
    UPDATED_AT	NUMBER NOT NULL,
    CONSTRAINT UK_MERCHANT_ENTITY_GROUP UNIQUE (MID, ENTITY_ID), -- Unique KEY
    CONSTRAINT FK_MERCHANT_ENTITY_GROUP FOREIGN KEY (MID) REFERENCES MERCHANT_INFO(MID) -- Foreign Key to `merchant_info` table
);




INSERT INTO MERCHANT_ENTITY_GROUP (
    ID, 
    MID, 
    ENTITY_ID, 
    CREATED_BY, 
    CREATED_AT, 
    UPDATED_BY, 
    UPDATED_AT
) VALUES (
    SYS_GUID(),          -- Unique ID generated by the database
    'MID123456',         -- Replace with actual Merchant ID
    'ENTITY001',         -- Replace with actual Entity ID
    'AdminUser',         -- Created by (username or system user)
    1672531200,          -- Created timestamp (UNIX epoch time)
    'AdminUser',         -- Updated by (username or system user)
    1672531200           -- Updated timestamp (UNIX epoch time)
);



INSERT INTO MERCHANT_ENTITY_USER (
    ID, 
    USER_ID, 
    ENTITY_ID, 
    MID, 
    CREATED_BY, 
    CREATED_AT, 
    UPDATED_BY, 
    UPDATED_AT
) VALUES (
    SYS_GUID(),          -- Unique ID generated by the database
    '112233445566778899AABBCCDDEEFF00', -- Replace with actual User ID (RAW format)
    'ENTITY001',         -- Replace with actual Entity ID
    'MID123456',         -- Replace with actual Merchant ID
    'AdminUser',         -- Created by (username or system user)
    1672531200,          -- Created timestamp (UNIX epoch time)
    'AdminUser',         -- Updated by (username or system user)
    1672531200           -- Updated timestamp (UNIX epoch time)
);
